config/routes.rb
TrailerTank::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, skip: [:sessions]
  as :user do
    get 'sign_in', :to => "main#index", :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root :to => "main#index" 
  get "main/index"
  get "main/leaders"
  get "main/update_trailer"
  get "main/delete_trailer"
  get "main/search_by_title"
  get "main/queue"
  get "main/get_trailer"
  get "main/mark_cant_find"
  get "main/cant_find"
  get "main/action_trailers"
  get "main/from_txt_test"
  get "main/change_role"
  get "main/add_record"
  get "main/manual_add"
  get "main/random_trailers"
  get "main/check_video"
  get "main/trailer_dump"
 

  

end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_title, :against => [:title]
  belongs_to :user 
  validates_uniqueness_of :record_id
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  before_action :set_trailer, only: [:show, :edit, :update, :destroy]

  # GET /trailers
  # GET /trailers.json
  def index
    @trailers = Trailer.all
  end

  # GET /trailers/1
  # GET /trailers/1.json
  def show
  end

  # GET /trailers/new
  def new
    @trailer = Trailer.new
  end

  # GET /trailers/1/edit
  def edit
  end

  # POST /trailers
  # POST /trailers.json
  def create
    @trailer = Trailer.new(trailer_params)

    respond_to do |format|
      if @trailer.save
        format.html { redirect_to @trailer, notice: 'Trailer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trailer }
      else
        format.html { render action: 'new' }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trailers/1
  # PATCH/PUT /trailers/1.json
  def update
    respond_to do |format|
      if @trailer.update(trailer_params)
        format.html { redirect_to @trailer, notice: 'Trailer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailers/1
  # DELETE /trailers/1.json
  def destroy
    @trailer.destroy
    respond_to do |format|
      format.html { redirect_to trailers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trailer
      @trailer = Trailer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trailer_params
      params.require(:trailer).permit(:record_id, :added_by, :youtube_url, :release_date, :tile, :artist)
    end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<%= form_for(@trailer) do |f| %>
  <% if @trailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trailer.errors.count, "error") %> prohibited this trailer from being saved:</h2>

      <ul>
      <% @trailer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :record_id %><br>
    <%= f.number_field :record_id %>
  </div>
  <div class="field">
    <%= f.label :added_by %><br>
    <%= f.text_field :added_by %>
  </div>
  <div class="field">
    <%= f.label :youtube_url %><br>
    <%= f.text_field :youtube_url %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.text_field :release_date %>
  </div>
  <div class="field">
    <%= f.label :tile %><br>
    <%= f.text_field :tile %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editing trailer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trailer %> |
<%= link_to 'Back', trailers_path %>

app/views/trailers/index.html.erb
<h1>Listing trailers</h1>

<table>
  <thead>
    <tr>
      <th>Record</th>
      <th>Added by</th>
      <th>Youtube url</th>
      <th>Release date</th>
      <th>Tile</th>
      <th>Artist</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trailers.each do |trailer| %>
      <tr>
        <td><%= trailer.record_id %></td>
        <td><%= trailer.added_by %></td>
        <td><%= trailer.youtube_url %></td>
        <td><%= trailer.release_date %></td>
        <td><%= trailer.tile %></td>
        <td><%= trailer.artist %></td>
        <td><%= link_to 'Show', trailer %></td>
        <td><%= link_to 'Edit', edit_trailer_path(trailer) %></td>
        <td><%= link_to 'Destroy', trailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trailer', new_trailer_path %>

app/views/trailers/new.html.erb
<h1>New trailer</h1>

<%= render 'form' %>

<%= link_to 'Back', trailers_path %>

app/views/trailers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Record:</strong>
  <%= @trailer.record_id %>
</p>

<p>
  <strong>Added by:</strong>
  <%= @trailer.added_by %>
</p>

<p>
  <strong>Youtube url:</strong>
  <%= @trailer.youtube_url %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @trailer.release_date %>
</p>

<p>
  <strong>Tile:</strong>
  <%= @trailer.tile %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @trailer.artist %>
</p>

<%= link_to 'Edit', edit_trailer_path(@trailer) %> |
<%= link_to 'Back', trailers_path %>